### PR TITLE
No autoconnect to Nearby Device

### PR DESCRIPTION
**Pull request by emilsas**
In a project I'm using the auto join policy "origin_scoped", so in Android this plugin try to join a session from any Chromecast that had been discovered.
But if you aren't in the same network of your Cast devices, a dialog of connect to a Nearby Device is prompted every time the plugin check if you can connect to an active Chromecast Session.\

The following code does not connect automatically if a Device is a "Nearby Device"

### CODE REVIEW

**Comment by lewazo** [comment]
I guess this would happen when a Chromecast has the guest mode enabled, is that right?

**Comment by emilsas** [comment]
@lewazo yes and no. Because my Chromecast app has Guest Mode disable, but the plugin is trying to connect to a Nearby Device besides the Guest Mode status.

**Comment by lewazo** [comment]
Right, well I think this addition makes sense.

**Edit:** I tested your branch and it works great with the jellyfin-android app.

**Review by lewazo — APPROVED** [review]

**Review by thornbill — APPROVED** [review]

**Comment by Lindsay-Needs-Sleep** [comment]
I am looking to merge this to 1.0.0 as well.  But I don't understand the problem I think.

Is it trying to:

- automatically join an existing session on the nearby device?
- or automatically create and join a new session on the nearby device?

**Comment by lewazo** [comment]
Create and join a new session on the nearby device.

Like how currently it creates and join a session when discovering devices on your network, well it did that too with nearby devices. You can still create a session to a nearby device by selecting it in the dialog, but it won't automatically create a session.

**Comment by Lindsay-Needs-Sleep** [comment]
Interesting.  (I never had it autojoin for me, so I wasn't sure.)

I *think* this type of autojoin doesn't follow the Chrome SDK spec.  

What I understand from the chromecast documentation, (and my testing on chrome browser):

- The autojoin policy only takes effect if you:
  - Have previously started/joined a session on a chromecast device 
  - AND that session is still active on the chromecast device.  
- Then, on initialize, it will attempt to rejoin the existing session. (Depending on the autojoin policy.)
- If there was no session, it will not try to create one, no matter the autojoin policy.

image

This is how I have implemented it in 1.0.0 (except it currently ignores the autojoin policy, because the app just does it automatically when the CastContext is initialized.  It might be possible to work in the autojoin policy later.)

One of my goals with 1.0.0 is to follow the Chrome Spec much closer.   So this fix is really applicable.

In 1.0.0, the autojoin you described, can be accomplished client-side using the `startRouteScan`/`stopRouteScan`/`selectRoute` methods if desired.  So the capability to do this will still exist.  (The routes outputted by `startRouteScan` also come with an `isNearby` flag, so it is possible to filter out the nearby devices already too!)

Thank you for explaining!

**Pull request merged**
