### PR TITLE
[New Feature] Support for iOS

### PR DESCRIPTION
**Pull request by emilsas**
Hi,

New implementation of this plugin for iOS.
The behaviour in iOS is the same than in Android, and it was coded in Swift using the new SDK of Google Cast.

Commented in PR #15 with @thornbill

### CODE REVIEW

**Comment by dkanada** [comment]
@emilsas thanks for always adding your changes here! I unfortunately have no experience with Swift so I probably shouldn't review this, but I will see if anyone else here has iOS experience. Also, could you run the commands below to clean out the merge commits from this pull request? There might be conflicts since you are using a separate master branch which may have changes we don't but its worth a shot.

```
git checkout feature/plugin-ios
git rebase master feature/plugin-ios
git push
```

**Comment by emilsas** [comment]
@dkanada Ok, it is a pity that we cannot review this PR. I don't know if you want to maintain this PR open or no, but we will maintain this feature in our fork because we are using it in iOS.

**Comment by ghenry22** [comment]
@emilsas why did you split the mute/volume level changes into seperate variables in the JS? surely they could be pushed back to the native layer the way they are and then assessed and split out as needed there which would remove the need for that change in the current JS.

edit - Actually I see the same return change made in a prior PR for the android code so all good there.  You're right choosing cancel isn't an error it's a valid option.

Similarly with the change to the return type on the request session, I can understand why you made the change but that then makes the iOS and Android implementations different.  Perhaps a better way would be to keep the existing behaviour as it is but add information in the docs or js comments that when an the err callback is called with an err object with message/description as cancel then handle this.

This then removes the need for any changes on the JS code for now and should keep Android and iOS working consistently.  Which will make this easier to merge as it doesn't risk breaking anything for existing users.

I am happy to take a look at this as well and help with testing on iOS and squashing the PR as needed for neatness so it can be merged.  I have previously released an iOS only chromecast plugin and I think it would be GREAT to get this merged so that there is one complete plugin that a community effort can build around.

**Comment by anthonylavado** [comment]
@ghenry22 - If you submit a review, though it won't "officially" count, we will use it to guide our own review :+1:

**Comment by DrPandemic** [comment]
@emilsas we currently can't test your code on our cordova app. Do you have a sample app that we could use to test it?

**Comment by ghenry22** [comment]
I have started testing from the qualabs fork.  Looks mostly good but found a couple of things, I can make an additional/new PR incorporating these or @emilsas can add to this one and I can wrap up some of the edge bits like docs and tests.

Then this should be good to go without breaking anything.

1) include the cordova-plugin-add-swift-support as a dependency in plugin.xml.  Else builds fail on iOS
https://www.npmjs.com/package/cordova-plugin-add-swift-support

2) the emitAllRoutes native method is not implemented on iOS.  JS calls it on interval which throws errors on interval on iOS as there is no native method there.  This just needs to emit the currently available device list on iOS to get similar behavior to Android.

3) you need to add the wifi permissions through the developer portal on iOS for your specific appID, it cannot be added or enabled for a wildcard ID.  Without this builds fail with an error that the provisioning profile doesn't have the required entitlement "wifi information etc..." Easily fixed but needs to be documented.

Not specific to iOS and this PR

4) tests show calling media.stop and session.stop as the way to disconnect.  Need to also call session.leave() otherwise you don't actually disconnect.

5) readme.md needs better documentation and usage examples.

I will submit a PR with updated readme with usage examples and details to address 3&5.

I will also submit a PR to adjust the tests as per 4.

**Comment by anthonylavado** [comment]
Thanks all. I’m going to approve this as-is then, since it shouldn’t hurt our Android usage of it. If there’s anything else for iOS @ghenry22 or @emilsas, please let us know.

**Review by anthonylavado — APPROVED** [review]

**Comment by emilsas** [comment]
Thanks a lot @anthonylavado, I'll review all the comments of @ghenry22 and keep all of you updated.

**Pull request merged**
