### PR TITLE
Update cast library so that it doesn't conflict with the androidx lib…

### PR DESCRIPTION
**Pull request by Sel-en-ium**
…raries.

Fixes issue#26 https://github.com/jellyfin/cordova-plugin-chromecast/issues/26

### CODE REVIEW

**Comment by Sel-en-ium** [comment]
Before approval, I would like to make sure I understand first...

Maybe the reason the plugin works for you guys is because of these instructions from the readme?

```
If you have NodeJS installed, the dependencies should be automatically copied. Otrherwise, you will need to import the following projects as Library Projects in order for this plugin to work.

- `adt-bundle\sdk\extras\google\google_play_services\libproject\google-play-services_lib`
- `adt-bundle\sdk\extras\android\support\v7\appcompat`
- `adt-bundle\sdk\extras\android\support\v7\mediarouter`
```

I did not have to manually add these or anything and it appears to be working.  (I guess because I **do** have node installed...)
Is it actually possible (common?) Cordova development without having node installed?

I have removed this from the readme.  But let me know if it should actually stay!

**Review by guilhermelirio — COMMENTED** [review]
I`m changed files, but errors occured:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.cast.MediaInfo.getContentId()' on a null object reference
	at acidhax.cordova.chromecast.ChromecastSession.createMediaInfoObject(ChromecastSession.java:534)
	at acidhax.cordova.chromecast.ChromecastSession.createMediaObject(ChromecastSession.java:570)
	at acidhax.cordova.chromecast.ChromecastSession.onStatusUpdated(ChromecastSession.java:687)
	at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source:70)
	at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source:90)
	at com.google.android.gms.cast.zzav.onStatusUpdated(Unknown Source:2)
	at com.google.android.gms.internal.cast.zzdn.onStatusUpdated(Unknown Source:630)
	at com.google.android.gms.internal.cast.zzdn.zzp(Unknown Source:531)
	at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source:88)
	at com.google.android.gms.internal.cast.zzcz.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.google.android.gms.internal.cast.zzep.dispatchMessage(Unknown Source:6)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by Lindsay-Needs-Sleep** [comment]
Interesting.  :S

Thank you for reviewing this! (and posting the error)

I will try it from a fresh project.  Not sure why that would happen.  

(I am pretty busy atm, so it might be a week or two before I update.  Just fy. I do intend to fix this!)

**Comment by Sel-en-ium** [comment]
I think I will actually drop this.  Lindsay-Needs-Sleep has a branch which encompasses this and intends issue a pull request eventually.

**Comment by Lindsay-Needs-Sleep** [comment]
Sel-en-ium and I were working together a bit, but she doesn't have time to do anymore.  

These changes appear to be working for me, but I have built quite a bit more on since then.  I am really low on time, so I'm not sure if I will be able to go back and isolate this issue.

I mentioned to her that I hope to issue a pull request once I've finished my changes for a new version of the plugin.  There are so many changes and I don't have time to make a request for each (especially since it wasn't completely passing the tests each commit [since none of tests passed to start with basically]).

**Pull request closed without merging**
